### ISSUE TITLE
Additional user-defined Update Timers

### ISSUE THREAD

**Issue by Hacktix** [Chroma-2D/Chroma#27]
While maybe slightly limited in usability, in some instances it could be nice to have seperate timers running on different frequencies to update game status. While this is technically possible in it's current state, being able to simply do something along the lines of this would be pretty cool:
```csharp
new UpdateTimer(100, () => {
    // some code that's called 100 times per second
}).Start();
```

**Comment by Ciastex** [comment]
closing, because of the FixedUpdate mechanism fundamentally changing since this was created - issue no longer relevant
