### ISSUE TITLE
[bug report] Window.Handle returns a non-existent window handle

### ISSUE THREAD

**Issue by nolemretaWxd** [Chroma-2D/Chroma#76]
**what broke**
`Window.Handle` property returns a non-existent window handle.

**how can the dev break it**
1. Try to get Chroma window handle with `Window.Handle`

**what should actually happen instead of y'know... breaking**
`Window.Handle` should return actual window handle

**got any screenshots?**
Screenshot from WinLister which lists currently open windows, and among other things, their handles
![obraz](https://github.com/Chroma-2D/Chroma/assets/31414969/0b3f35f5-0b0b-4449-a923-d1256f219275)

**environment (complete the following):**
 - OS: Windows 11 22621.1992

**additional context? remarks?**
```
[23:46:25 INF] [Log] 2096835469184
[23:46:25 INF] [Log] 791466
```

First handle is the one that's returned from `Window.Handle`, and 2nd one is from GetForegroundWindow() function in user32.dll. And as indicated by WinLister, the 2nd window handle is the one that's correct

**Comment by vddCore** [comment]
fixed with 0f5a8a
